kind: Namespace
apiVersion: v1
metadata:
  name: siim-aarmaa
  labels: 
    name: siim-aarmaa
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: siim-config
  namespace: siim-aarmaa
data:
  happy: "true"
  message: "I love pets"
