kind: Namespace
apiVersion: v1
metadata:
  name: Siim-Aarmaa-Pod
  labels: 
    name: Siim-Aarmaa-Pod
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: pod-config
  namespace: Siim-Aarmaa-Pod
data:
  happy: "true"
  message: "I love pets"
