kind: Namespace
apiVersion: v1
metadata:
  name: siim-aarmaa-pod
  labels: 
    name: siim-aarmaa-pod
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: siim-pod-config
  namespace: siim-aarmaa-pod
data:
  happy: "true"
  message: "I love pets"
