kind: Namespace
apiVersion: v1
metadata:
  name: SiimAarmaaPod
  labels: 
    name: SiimAarmaaPod
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: pod-config
  namespace: SiimAarmaaPod
data:
  happy: "true"
  message: "I love pets"
